openapi: 3.0.3
info:
  title: API Prochild
  version: 1.1.0
  description: API para gerenciamento de treinamentos, seções, categorias, usuários e centros de saúde

servers:
  - url: http://127.0.0.1:8000
    description: Servidor Local

paths:
  /users/:
    get:
      summary: Listar todos os usuários
      responses:
        '200':
          description: Lista de usuários

  /users/register/:
    post:
      summary: Registrar novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: Usuário registrado com sucesso

  /users/login/:
    post:
      summary: Login do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login realizado

  /users/{user_id}/:
    get:
      summary: Buscar usuário por ID
      responses:
        '200':
          description: Usuário retornado

  /users/edit/{user_id}/:
    put:
      summary: Editar usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Usuário atualizado

  /users/delete/{user_id}/:
    delete:
      summary: Deletar usuário
      responses:
        '200':
          description: Usuário deletado

  /users/reset-password/:
    post:
      summary: Solicitar redefinição de senha
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Token de recuperação enviado

  /users/set-new-password/:
    post:
      summary: Redefinir senha com token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                nova_senha:
                  type: string
      responses:
        '200':
          description: Senha redefinida com sucesso

  /sections/:
    get:
      summary: Listar todas as seções
      responses:
        '200':
          description: Lista de seções retornada
    post:
      summary: Criar nova seção
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        '201':
          description: Seção criada com sucesso

  /sections/{section_id}/:
    get:
      summary: Buscar seção por ID
      responses:
        '200':
          description: Seção retornada

  /sections/edit/{section_id}/:
    put:
      summary: Editar seção
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        '200':
          description: Seção editada

  /sections/delete/{section_id}/:
    delete:
      summary: Deletar seção
      responses:
        '200':
          description: Seção deletada

  /categories/:
    get:
      summary: Listar todas as categorias
      responses:
        '200':
          description: Lista de categorias
    post:
      summary: Criar nova categoria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                secao_id:
                  type: integer
                nome:
                  type: string
                cor:
                  type: string
                icone_id:
                  type: string
      responses:
        '201':
          description: Categoria criada com sucesso

  /categories/section/{section_id}/:
    get:
      summary: Buscar categorias por seção
      responses:
        '200':
          description: Lista filtrada

  /categories/{category_id}/:
    put:
      summary: Editar categoria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                cor:
                  type: string
                icone_id:
                  type: string
                secao_id:
                  type: integer
      responses:
        '200':
          description: Categoria atualizada
    delete:
      summary: Deletar categoria
      responses:
        '200':
          description: Categoria deletada

  /trainings/:
    get:
      summary: Listar todos os treinamentos
      responses:
        '200':
          description: Lista de treinamentos
    post:
      summary: Criar novo treinamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoria_id:
                  type: integer
                titulo:
                  type: string
                tamanho:
                  type: string
                descricao:
                  type: string
                arquivo_nome:
                  type: string
                arquivo_caminho:
                  type: string
      responses:
        '201':
          description: Treinamento criado com sucesso

  /trainings/{training_id}/:
    get:
      summary: Buscar treinamento por ID
      responses:
        '200':
          description: Detalhes do treinamento

  /trainings/edit/{training_id}/:
    put:
      summary: Atualizar treinamento existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                categoria_id:
                  type: integer
                titulo:
                  type: string
                descricao:
                  type: string
                arquivo_nome:
                  type: string
                arquivo_caminho:
                  type: string
                tamanho:
                  type: string
      responses:
        '200':
          description: Treinamento atualizado com sucesso

  /trainings/delete/{training_id}/:
    delete:
      summary: Deletar treinamento
      responses:
        '200':
          description: Treinamento deletado

  /trainings/by-category/{category_id}/:
    get:
      summary: Buscar treinamentos por categoria
      responses:
        '200':
          description: Treinamentos por categoria

  /trainings/deleteall/{category_id}/:
    delete:
      summary: Deletar todos os treinamentos de uma categoria
      responses:
        '200':
          description: Treinamentos deletados

  /healthcenters/healthcenters/:
    get:
      summary: Listar centros de saúde do usuário autenticado
      responses:
        '200':
          description: Lista de centros
    post:
      summary: Criar novo centro de saúde
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                telefone:
                  type: string
      responses:
        '201':
          description: Centro criado

  /healthcenters/{id}/:
    get:
      summary: Buscar centro de saúde por ID
      responses:
        '200':
          description: Detalhes do centro
    put:
      summary: Atualizar centro de saúde
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                telefone:
                  type: string
      responses:
        '200':
          description: Centro atualizado
    delete:
      summary: Remover centro de saúde
      responses:
        '200':
          description: Centro removido
