# Generated by Django 5.2.1 on 2025-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categories_icone_id_alter_categories_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
