# Generated by Django 5.2.1 on 2025-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
