# Generated by Django 5.2 on 2025-04-26 01:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('arquivo_caminho', models.CharField(blank=True, max_length=255, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='categories.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_download', models.DateTimeField(default=django.utils.timezone.now)),
                ('treinamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='trainings.training')),
            ],
        ),
    ]
