# Generated by Django 5.2 on 2025-04-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('trainings', '0002_training_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='secao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='sections.section'),
        ),
    ]
