# Generated by Django 5.2 on 2025-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_training_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='arquivo_caminho',
            field=models.FileField(blank=True, null=True, upload_to='trainings/files/'),
        ),
    ]
